version: '3.7'

services:
 client:
  ports:
  - "80:3000"
  - "3000:3000"
  expose: 
  - 3000
  build:
   context: ./client
 server-nest:
  expose:
   - 3002
  build:
   context: ./server-nest
  ports:
   - "3002:3002"
