name: "deploy"

on:
  push:
    branches:
      [ "main" ]
  
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make kill-containers.sh executable
        run: chmod +x kill-containers.sh

      - name: Kill docker containers
        run: ./kill-containers.sh
        shell: bash

      - name: Copy over env file to server-nest folder of cloned repo
        run: cp ~/actions-runner/persist/.env $(pwd)/server-nest
        shell: bash

      - name: Confirm that copying .env file worked (should output 'it-worked')
        run: cat server-nest/.env | grep "TEST_VAR.*" | cut -d "=" -f2
        shell: bash

      - name: Spin up docker containers
        run: docker compose up --detach --build
