name: "deploy"

on:
  push:
    branches:
      [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop old containers
        run: docker-compose rm -f
        
      - name: Copy over env file to server-nest folder of cloned repo
        run: cp ~/actions-runner/persist/.env $(pwd)/server-nest
        shell: bash

      - name: Confirm that copying .env file worked (should output 'it-worked')
        run: cat server-nest/.env | grep "TEST_VAR.*" | cut -d "=" -f2
        shell: bash
        
      - name: Pull latest Docker images
        run: docker-compose pull

      - name: Spin up docker containers
        run: docker-compose up --build -d --force-recreate

#      - name: Make kill-containers.sh executable
#        run: chmod +x kill-containers.sh

#      - name: Kill docker containers
#        run: ./kill-containers.sh
#        shell: bash
