name: "kill-containers"

on:
  workflow_dispatch:

jobs:
  kill-lira:
    name: kill-containers
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make kill-containers.sh executable
        run: chmod +x kill-containers.sh

      - name: Kill docker containers
        run: ./kill-containers.sh
        shell: bash
